[package]
name = "musicquiz"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
regex = "1.5"
strum = "0.21"
strum_macros = "0.21"
console = "0.14.1"
